# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses:  actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start update (with retry)
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
      run: |
        n=0
        until [ "$n" -ge 3 ]
        do
          python3 main.py && break
          n=$((n+1))
          echo "Attempt $n failed, retrying in 5 seconds..."
          sleep 5
        done
        if [ "$n" -ge 3 ]; then
          echo "Update failed after 3 attempts."
          exit 1
        fi
